### ISSUE TITLE
Content errors

### ISSUE THREAD

**Issue by Lussitonic** [Sheep-Hugger/Frozen-Silver-Fortress#2]
![image](https://user-images.githubusercontent.com/98243595/152698037-e8f299ee-2ab6-4634-a20d-f522b652d421.png)
need i say more? 
Well, if you need me to, I can?

**Comment by Sheep-Hugger** [comment]
this mod is mainly in dev for V7.

some feature dont even work on the alpha build as its dev-ed for the latest one in mind

Note this mod will not work on Ios

**Comment by Lussitonic** [comment]
I Am indeed using V7, and am on PC. Operating system is Windows.

**Comment by Sheep-Hugger** [comment]
yeah no clue should be fixed ether way i purged all the console errors twice over now
